

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - /app/.venv
    env_file:
      - .env
    environment:
      FILESYSTEM_MCP_URL: http://mcp_servers:9001
      TIME_MCP_URL: http://mcp_servers:9002
      CALC_MCP_URL: http://mcp_servers:9003
      MARKDOWN_MCP_URL: http://mcp_servers:9004
      GITHUB_MCP_URL: http://mcp_servers:9005
    depends_on:
      - postgres
      - qdrant
      - mcp_servers
    command: ["uvicorn", "backend.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

  mcp_servers:
    build:
      context: .
      dockerfile: backend/Dockerfile
    command: ["python", "-m", "mcp_servers"]
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/.venv
    ports:
      - "9001:9001"
      - "9002:9002"
      - "9003:9003"
      - "9004:9004"
      - "9005:9005"

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"
    depends_on:
      - postgres

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  postgres_data:
  qdrant_data:
