- name: filesystem
  transport: http
  url: http://localhost:9001
- name: time
  transport: http
  url: http://localhost:9002
- name: calculator
  transport: http
  url: http://localhost:9003
- name: markdown_backup
  transport: http
  url: http://localhost:9004
- name: github
  transport: http
  url: http://localhost:9005
- name: docs
  transport: http
  url: http://localhost:9006
- name: query
  transport: http
  url: http://localhost:9007
