database:
  postgres_uri: "postgresql://user:password@postgres:5432/axon_db"
  qdrant_host: "qdrant"
  qdrant_port: 6333
  redis_url: "redis://redis:6379/0"

llm:
  default_local_model: "qwen3:8b"
  qwen_agent_generate_cfg:
    fncall_prompt_type: "nous"

app:
  mcp_mode: false
  mcp_log_path: "mcp_traffic.json"
  api_token: null
  rate_limit_per_minute: 60
  proactive_scan_minutes: 30
