database:
  postgres_uri: "postgresql://user:password@localhost:5432/axon_db"
  sqlite_path: "data/axon.db"
  qdrant_host: "localhost"
  qdrant_port: 6333
  redis_url: "redis://localhost:6379/0"

llm:
  default_local_model: "openrouter/horizon-beta"
  model_server: "https://openrouter.ai/api/v1"
  qwen_agent_generate_cfg:
    fncall_prompt_type: "nous"

app:
  mcp_mode: false
  mcp_log_path: "mcp_traffic.json"
  api_token: null
  rate_limit_per_minute: 60
  proactive_scan_minutes: 30
  log_level: "info"
