database:
  postgres_uri: "postgresql://user:password@localhost:5432/axon_db"
  qdrant_host: "localhost"
  qdrant_port: 6333

llm:
  default_local_model: "qwen3:8b"
  qwen_agent_generate_cfg:
    fncall_prompt_type: "nous"

app:
  mcp_mode: false
  mcp_log_path: "mcp_traffic.json"
  api_token: "change-me"
  rate_limit_per_minute: 60
