# .github/workflows/ci.yml

name: Python CI

on:
  push:
    branches: [ "main", "develop" ] # Triggers on push to main or develop
  pull_request:
    branches: [ "main" ] # Triggers on pull requests to main

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        virtualenvs-create: true
        virtualenvs-in-project: true

    - name: Install dependencies
      run: |
        poetry install --no-interaction --no-root

    - name: Lint with ruff
      run: |
        poetry run ruff check .

    - name: Type check with mypy
      run: |
        # We need to install stubs for libraries that don't have inline types
        poetry run pip install types-pyyaml
        poetry run mypy .

    - name: Run tests
      run: |
        poetry run pytest -q
